### PR TITLE
Required functions for ros2 humble

### PR DESCRIPTION
**Pull request by jasperdekeuk**
Minimum implementation for required function to make rmw_ecal runnable for ROS2 Humble distro.
Should definitely be checked by someone with more ROS experience, and probably need certain implementation in these functions.

### CODE REVIEW

**Comment by jasperdekeuk** [comment]
related to #56

**Comment by FlorianReimold** [comment]
Thank you very much for contributing this! 🙌
However it looks like something broke on foxy and galactic? Maybe you could take a look if that is fixable...

----

Before merging I also have to ask you to sign the Eclipse Contributor Agreement. The way that works is:

1. You create an Eclipse Account https://accounts.eclipse.org/user/register?destination=user/edit
2. You go to your Account settings, scroll down and add your GitHub Username in the "Social Media Links" Section:
    image
3. You go to http://www.eclipse.org/contribute/cla and complete the form to electronically sign the Contributor Agreement

_Sorry for the hassle, this is the common Eclipse Foundation process that we have to follow for non-trivial PRs 😶_

**Comment by jasperdekeuk** [comment]
Not sure if this fix is sufficient, unfortunately don't have older ros distros at hand for testing

**Comment by FlorianReimold** [comment]
Hm, the GH Actions failed (except for humble), so probably not

**Comment by jasperdekeuk** [comment]
I approved for the Eclipse legal agreements, but somehow also keeps failing?

**Comment by FlorianReimold** [comment]
> I approved for the Eclipse legal agreements, but somehow also keeps failing?

Oh well, I somethimes hate that check 😫

Some of your commits come from 
grafik
while some others from 
grafik

From what I can see, only the former one got covered by the Eclipse ECA 🙄

**Comment by FlorianReimold** [comment]
It looks like this works now, on all ROS distros!

Unfortunately you had some kind of auto-code-formatter do it's work on the code base, so I totally lost track on what has changed. We usually have our codebase with 2-space-indentations and a line-break between the function parameters and the opening curly brace.

Is there any way to roll back that reformatting? I find it unnecessary for this commit.

**Comment by FlorianReimold** [comment]
Hey, looks like something broke again, fur Humble:
image

BTW: How did you get the eclipsefdn/eca to recognize both of your email addresses?

**Comment by jasperdekeuk** [comment]
I deleted my github name from the first account, made a new account for the second mail address and assigned my github name to that account. Afterwards I did the check and it failed again so I gave up. But now somehow it seems to be ok. 😌 
The issue seems to be that the Eclipse account doesn't allow multiple mail addresses to be assigned to the same github name..

**Comment by FlorianReimold** [comment]
Merged it! Thanks for contributing 😊

**Pull request merged**
