### PR TITLE
Change message namespace from proto: to package namespace for rmw_eca…

### PR DESCRIPTION
**Pull request by karthiknit1**
…l_proto_cpp

### CODE REVIEW

**Comment by FlorianReimold** [comment]
Thanks for fixing this! It looks totally reasonable and I don't know why it wasn't implemented like that from the beginning.

I just have 1 Question about removing the `proto:` prefix entirely. In eCAL it is common practice to prefix the topic type with the Serialization (see screenshot below). Would there be any (negative) implications to keep the `proto:` prefix in rmw_ecal as well and make it something like:
`"proto:" + GetMessageNamespace() + "/" + GetMessageSimpleName()`?

image

**Comment by karthiknit1** [comment]
Hi Florian,

The reason behind completely removing the "proto:" string is that, when we use eCAL  to communicate with other dds such as RTI Connext (with ROS or just standalone DDS), there will be a message type mismatch. For example, "proto:String" incase of eCAL and "std_msgs/String" incase of RTI Connext. Other reason is that, if we see any other rmw implementation package, such as rmw_connext_cpp (older connext), which is based on static rosidl type support, the message types are just prepended by package namespace, which is "std_msgs/" incase of "String.msg". 

Also, if we look at eCAL monitor, I am not sure about the purpose of "proto:" in the screenshot. This "proto:" string in the eCAL monitor doesn't really make much sense to me here. 

Thanks,
Karthik Reddy

**Comment by karthiknit1** [comment]
Hi Florian,

Thanks for providing more information on the issue if we remove "proto:". Along with "proto:" it is the right way to also have message package name. I quickly tested it with ROS 2 as well by following the  workaround of removing "proto:" but keeping 
GetMessageNamespace() + "/" + GetMessageSimpleName(). I have updated the pull request on the same, please do take a look. I quickly tested the change and saw the output on eCAL monitor as follows. I don't see any negative implications.

image


Thanks,
Karthik Reddy

**Comment by FlorianReimold** [comment]
Hey Karthik,

The current state is the solution I had hoped for. So if you didn't see negative implications on compatibility with ROS, I will merge it as-is.

Oh, one last question: Is there a possibility that the message namespace can be empty string? Because in that case we would have to omit the `/`.

Kind Regards
Florian

**Comment by karthiknit1** [comment]
Hi Florian, 

I couldn't think of a case where the message namespace can be an empty string. However, I would like to go with how it is done for rmw_ecal_dynamic_cpp. There I don't see a check for empty string in message namespace. For your reference, here is the code snippet - https://github.com/eclipse-ecal/rmw_ecal/blob/master/rmw_ecal_dynamic_cpp/src/typesupport/message_typesupport_cpp.hpp#:~:text=virtual%20const%20std%3A%3Astring%20GetMessageName,%7D

Thanks,
Karthik Reddy

**Pull request merged**
